#!/bin/bash
# gid: git delete branch (local & remote)

   if [ "$*" == "-?" ]; then
      echo '   usage: gid -! <branch>      # git delete branch (local & remote)'
      echo '          gid Bluco-V10.00'
      echo '   see also: gid, gik, gil, gip, gir, gis, giu, chk, tag'
      exit 1
   fi

   if [ "$1" != "-!" ]; then
      gid -?
      exit 1
   fi

   if [ "$2" == "" ]; then
      gid -?
      exit 1
   fi

# deleting branch

   echo "deleting branch ..."
   echo "   delete local branch: git branch -D $2"
   git branch -D $2 || exit

   echo "   delete remote branch: git push origin --delete $2"
   git push origin --delete $2 || exit
