#!/bin/bash
# gip: git push origin

   if [ "$*" == "-?" ]; then
      echo '   usage: gip            # git push origin'
      echo '          gip -i         # git push --set-upstream origin ihux'
      echo '          gip <branch>   # git push origin <branch>'
      echo '   see also: gid, gik, gil, gip, gir, gis, giu, chk, tag'
      exit 1
   fi

   if [ "$*" == "-i" ]; then
      git push --set-upstream origin ihux
      exit 0
   fi

   echo "git push origin $*"
   git push origin $*
