#!/bin/bash
# gir: git rename branch (local & remote)

   if [ "$*" == "-?" ]; then
      echo '   usage: gir <old> <new>    # git rename branch (local & remote)'
      echo '          gir Bluco-V10.00 Bluco-V10.00.0'
      echo '   see also: gid, gik, gil, gip, gir, gis, giu, chk, tag'
      exit 1
   fi

   if [ "$1" == "" ]; then
       gir -?; exit 1
   fi

   if [ "$2" == "" ]; then
       gir -?; exit 1
   fi
   if [ "$3" != "" ]; then
       gir -?; exit 1
   fi

# rename local name of branch

   echo "renaming local branch $1 to $2 ..."
   echo "   checkout branch to rename: git checkout $1"
   git checkout $1 || exit

   echo "   rename local branch: git branch -m $2"
   git branch -m $2  || exit


# rename global name of branch

   echo "renaming global branch $1 to $2 ..."
   echo "   change remote: git push origin :$1 $2"
   git push origin :$1 $2 || exit

   echo "   complete remote: git push origin -u $2"
   git push origin -u $2 || exit
