#!/bin/bash
# gis: git status (after git fetch)

   if [ "$*" == "-?" ]; then
      echo '   usage: gis    # git status (after git fetch)'
      echo '          gis -s # show some details'
      echo ''
      echo '   see also: gid, gik, gil, gip, gir, gis, giu, chk, tag'
      exit 1
   fi

   if [ "$*" == "-s" ]; then
      git show && exit
   fi

   ec -y '=> git status'
   git status
